import type { Instrument } from '../types.js';

/**
 * Tadawul (TASI) universe.
 * Symbols and names are reference data. `marketCap` values are approximate
 * static reference figures used only to size heatmap tiles — replace them with
 * feed-supplied caps once a licensed Saudi provider is wired up.
 * Caps are in billions of SAR.
 */
const raw: Array<[string, string, string, string, number]> = [
  // symbol, EN name, AR name, sector key, cap (bn SAR)
  ['2222', 'Saudi Aramco', 'أرامكو السعودية', 'energy', 6800],
  ['1120', 'Al Rajhi Bank', 'مصرف الراجحي', 'banks', 380],
  ['1180', 'Saudi National Bank', 'البنك الأهلي السعودي', 'banks', 210],
  ['2010', 'SABIC', 'سابك', 'materials', 210],
  ['7010', 'stc', 'الاتصالات السعودية', 'telecom', 210],
  ['1211', "Ma'aden", 'معادن', 'materials', 195],
  ['2020', 'SABIC Agri-Nutrients', 'سابك للمغذيات الزراعية', 'materials', 55],
  ['1010', 'Riyad Bank', 'بنك الرياض', 'banks', 85],
  ['1150', 'Alinma Bank', 'مصرف الإنماء', 'banks', 60],
  ['1060', 'Saudi Awwal Bank', 'البنك السعودي الأول', 'banks', 70],
  ['1050', 'Banque Saudi Fransi', 'البنك السعودي الفرنسي', 'banks', 48],
  ['1140', 'Bank Albilad', 'بنك البلاد', 'banks', 33],
  ['1080', 'Arab National Bank', 'البنك العربي الوطني', 'banks', 32],
  ['1020', 'Bank Aljazira', 'بنك الجزيرة', 'banks', 15],
  ['1030', 'SAIB', 'البنك السعودي للاستثمار', 'banks', 14],
  ['2280', 'Almarai', 'المراعي', 'consumer', 58],
  ['2350', 'Saudi Kayan', 'كيان السعودية', 'materials', 20],
  ['2380', 'Petro Rabigh', 'بترو رابغ', 'energy', 12],
  ['2290', 'Yanbu National Petrochemical', 'ينساب', 'materials', 21],
  ['2310', 'Sipchem', 'سبكيم العالمية', 'materials', 19],
  ['2330', 'Advanced Petrochemical', 'المتقدمة', 'materials', 8],
  ['2001', 'Chemanol', 'كيمانول', 'materials', 2],
  ['2060', 'Industrialization', 'التصنيع', 'industrial', 8],
  ['2270', 'SADAFCO', 'سدافكو', 'consumer', 11],
  ['6001', 'Halwani Bros', 'حلواني إخوان', 'consumer', 2],
  ['6010', 'NADEC', 'نادك', 'consumer', 8],
  ['4001', 'A.Othaim Markets', 'أسواق العثيم', 'consumer', 10],
  ['4190', 'Jarir Marketing', 'جرير', 'consumer', 16],
  ['4240', 'Fawaz Alhokair', 'الحكير', 'consumer', 4],
  ['4161', 'Bin Dawood', 'بن داود', 'consumer', 5],
  ['2050', 'Savola Group', 'صافولا', 'consumer', 20],
  ['4003', 'Extra', 'إكسترا', 'consumer', 9],
  ['5110', 'Saudi Electricity', 'كهرباء السعودية', 'utilities', 70],
  ['2081', 'Alkhorayef Water', 'الخريف للمياه', 'utilities', 5],
  ['2082', 'ACWA Power', 'أكوا باور', 'utilities', 200],
  ['7020', 'Etihad Etisalat (Mobily)', 'اتحاد اتصالات - موبايلي', 'telecom', 45],
  ['7030', 'Zain KSA', 'زين السعودية', 'telecom', 12],
  ['7040', 'Etihad Atheeb', 'اتحاد عذيب', 'telecom', 5],
  ['4013', 'Dr. Sulaiman Al Habib', 'د. سليمان الحبيب', 'healthcare', 100],
  ['4002', 'Mouwasat', 'المواساة', 'healthcare', 12],
  ['4004', 'Dallah Health', 'دله الصحية', 'healthcare', 9],
  ['4007', 'Al Hammadi', 'الحمادي', 'healthcare', 5],
  ['2140', 'Al Khaleej Training', 'الخليج للتدريب', 'consumer', 2],
  ['4020', 'Al Akaria', 'العقارية', 'realestate', 6],
  ['4090', 'Taiba Investments', 'طيبة', 'realestate', 7],
  ['4100', 'Makkah Construction', 'مكة للإنشاء', 'realestate', 15],
  ['4300', 'Dar Al Arkan', 'دار الأركان', 'realestate', 16],
  ['4250', 'Jabal Omar', 'جبل عمر', 'realestate', 22],
  ['4321', 'Arabian Centres (Cenomi)', 'سينومي سنترز', 'realestate', 10],
  ['1211.M', 'Alujain', 'اللجين', 'materials', 3],
  ['2170', 'Alujain Holding', 'اللجين القابضة', 'materials', 3],
  ['1301', 'United Wire Factories', 'أسلاك', 'industrial', 3],
  ['1320', 'SSP', 'الأنابيب السعودية', 'industrial', 2],
  ['2110', 'Saudi Cable', 'الكابلات', 'industrial', 1],
  ['3030', 'Saudi Cement', 'أسمنت السعودية', 'materials', 8],
  ['3020', 'Yamama Cement', 'أسمنت اليمامة', 'materials', 7],
  ['3040', 'Qassim Cement', 'أسمنت القصيم', 'materials', 6],
  ['3050', 'Southern Cement', 'أسمنت الجنوبية', 'materials', 6],
  ['4030', 'Bahri', 'البحري', 'industrial', 12],
  ['4200', 'Aldrees', 'الدريس', 'energy', 6],
  ['4260', 'Budget Saudi', 'بدجت السعودية', 'industrial', 4],
  ['4263', 'SAL Logistics', 'سال', 'industrial', 11],
  ['8010', 'Tawuniya', 'التعاونية', 'financials', 20],
  ['8210', 'Bupa Arabia', 'بوبا العربية', 'financials', 24],
  ['8012', 'Aljazira Takaful', 'الجزيرة تكافل', 'financials', 2],
  ['1111', 'Saudi Tadawul Group', 'تداول السعودية', 'financials', 25],
  ['1182', 'Amlak International', 'أملاك العالمية', 'financials', 3],
  ['4344', 'Sinad Holding', 'سناد القابضة', 'financials', 4],
  ['2223', 'Luberef', 'لوبريف', 'energy', 20],
  ['2382', 'Arabian Drilling', 'العربية للحفر', 'energy', 12],
  ['1833', 'Almawarid Manpower', 'الموارد', 'industrial', 3],
];

export const SAUDI_UNIVERSE: Instrument[] = raw.map(([symbol, nameEn, nameAr, sector, cap]) => ({
  id: `saudi:${symbol}`,
  market: 'saudi' as const,
  symbol,
  nameEn,
  nameAr,
  sector,
  currency: 'SAR' as const,
  marketCap: cap * 1e9,
}));

export const SAUDI_SECTORS = [
  'banks',
  'energy',
  'materials',
  'telecom',
  'healthcare',
  'realestate',
  'utilities',
  'consumer',
  'industrial',
  'financials',
] as const;
