import type { Instrument } from '../types.js';

/**
 * US universe (NASDAQ / NYSE). `marketCap` is approximate static reference data
 * in billions of USD, used only for heatmap tile sizing until a live feed
 * supplies real caps.
 */
const raw: Array<[string, string, string, string, number]> = [
  ['AAPL', 'Apple', 'أبل', 'technology', 3400],
  ['MSFT', 'Microsoft', 'مايكروسوفت', 'technology', 3300],
  ['NVDA', 'NVIDIA', 'إنفيديا', 'technology', 3200],
  ['GOOGL', 'Alphabet', 'ألفابت', 'technology', 2100],
  ['AMZN', 'Amazon', 'أمازون', 'consumer', 2000],
  ['META', 'Meta Platforms', 'ميتا', 'technology', 1400],
  ['AVGO', 'Broadcom', 'برودكوم', 'technology', 900],
  ['TSLA', 'Tesla', 'تسلا', 'consumer', 850],
  ['BRK.B', 'Berkshire Hathaway', 'بيركشاير هاثاواي', 'financials', 900],
  ['LLY', 'Eli Lilly', 'إيلي ليلي', 'healthcare', 800],
  ['JPM', 'JPMorgan Chase', 'جي بي مورغان', 'financials', 700],
  ['V', 'Visa', 'فيزا', 'financials', 620],
  ['UNH', 'UnitedHealth', 'يونايتد هيلث', 'healthcare', 520],
  ['XOM', 'Exxon Mobil', 'إكسون موبيل', 'energy', 500],
  ['MA', 'Mastercard', 'ماستركارد', 'financials', 480],
  ['COST', 'Costco', 'كوستكو', 'consumer', 400],
  ['JNJ', 'Johnson & Johnson', 'جونسون آند جونسون', 'healthcare', 390],
  ['HD', 'Home Depot', 'هوم ديبوت', 'consumer', 380],
  ['PG', 'Procter & Gamble', 'بروكتر آند غامبل', 'consumer', 390],
  ['ORCL', 'Oracle', 'أوراكل', 'technology', 470],
  ['AMD', 'Advanced Micro Devices', 'إيه إم دي', 'technology', 260],
  ['NFLX', 'Netflix', 'نتفليكس', 'technology', 300],
  ['CRM', 'Salesforce', 'سيلزفورس', 'technology', 260],
  ['ABBV', 'AbbVie', 'آبفي', 'healthcare', 320],
  ['BAC', 'Bank of America', 'بنك أوف أمريكا', 'financials', 320],
  ['KO', 'Coca-Cola', 'كوكا كولا', 'consumer', 280],
  ['PEP', 'PepsiCo', 'بيبسيكو', 'consumer', 240],
  ['CVX', 'Chevron', 'شيفرون', 'energy', 280],
  ['WMT', 'Walmart', 'وول مارت', 'consumer', 600],
  ['MRK', 'Merck', 'ميرك', 'healthcare', 250],
  ['ADBE', 'Adobe', 'أدوبي', 'technology', 220],
  ['QCOM', 'Qualcomm', 'كوالكوم', 'technology', 190],
  ['TXN', 'Texas Instruments', 'تكساس إنسترومنتس', 'technology', 180],
  ['INTC', 'Intel', 'إنتل', 'technology', 100],
  ['CSCO', 'Cisco', 'سيسكو', 'technology', 200],
  ['ACN', 'Accenture', 'أكسنتشر', 'technology', 200],
  ['MCD', "McDonald's", 'ماكدونالدز', 'consumer', 210],
  ['DIS', 'Walt Disney', 'ديزني', 'consumer', 180],
  ['WFC', 'Wells Fargo', 'ويلز فارغو', 'financials', 200],
  ['GS', 'Goldman Sachs', 'غولدمان ساكس', 'financials', 160],
  ['MS', 'Morgan Stanley', 'مورغان ستانلي', 'financials', 160],
  ['CAT', 'Caterpillar', 'كاتربيلر', 'industrial', 170],
  ['BA', 'Boeing', 'بوينغ', 'industrial', 110],
  ['GE', 'GE Aerospace', 'جنرال إلكتريك', 'industrial', 180],
  ['HON', 'Honeywell', 'هانيويل', 'industrial', 130],
  ['UPS', 'United Parcel Service', 'يو بي إس', 'industrial', 110],
  ['LMT', 'Lockheed Martin', 'لوكهيد مارتن', 'industrial', 110],
  ['RTX', 'RTX Corp', 'آر تي إكس', 'industrial', 150],
  ['DE', 'Deere & Co', 'ديري', 'industrial', 110],
  ['COP', 'ConocoPhillips', 'كونوكو فيليبس', 'energy', 130],
  ['SLB', 'SLB', 'شلمبرجير', 'energy', 60],
  ['EOG', 'EOG Resources', 'إي أو جي', 'energy', 70],
  ['PSX', 'Phillips 66', 'فيليبس 66', 'energy', 55],
  ['NEE', 'NextEra Energy', 'نكست إيرا', 'utilities', 150],
  ['DUK', 'Duke Energy', 'ديوك إنرجي', 'utilities', 85],
  ['SO', 'Southern Company', 'ساذرن', 'utilities', 95],
  ['AEP', 'American Electric Power', 'أمريكان إلكتريك', 'utilities', 50],
  ['PLD', 'Prologis', 'برولوجيس', 'realestate', 110],
  ['AMT', 'American Tower', 'أمريكان تاور', 'realestate', 90],
  ['EQIX', 'Equinix', 'إكوينكس', 'realestate', 80],
  ['SPG', 'Simon Property', 'سايمون بروبرتي', 'realestate', 55],
  ['O', 'Realty Income', 'ريالتي إنكم', 'realestate', 50],
  ['PFE', 'Pfizer', 'فايزر', 'healthcare', 150],
  ['TMO', 'Thermo Fisher', 'ثيرمو فيشر', 'healthcare', 200],
  ['ABT', 'Abbott Labs', 'أبوت', 'healthcare', 200],
  ['DHR', 'Danaher', 'دانهر', 'healthcare', 170],
  ['AMGN', 'Amgen', 'أمجين', 'healthcare', 150],
  ['NKE', 'Nike', 'نايكي', 'consumer', 110],
  ['SBUX', 'Starbucks', 'ستاربكس', 'consumer', 100],
  ['TGT', 'Target', 'تارغت', 'consumer', 65],
  ['LOW', "Lowe's", 'لوز', 'consumer', 140],
  ['PYPL', 'PayPal', 'باي بال', 'financials', 70],
  ['UBER', 'Uber', 'أوبر', 'technology', 150],
  ['SHOP', 'Shopify', 'شوبيفاي', 'technology', 110],
  ['PANW', 'Palo Alto Networks', 'بالو ألتو', 'technology', 120],
  ['MU', 'Micron', 'مايكرون', 'technology', 110],
  ['ARM', 'Arm Holdings', 'آرم', 'technology', 140],
  ['SMCI', 'Super Micro', 'سوبر مايكرو', 'technology', 25],
  ['COIN', 'Coinbase', 'كوين بيس', 'financials', 60],
  ['PLTR', 'Palantir', 'بالانتير', 'technology', 130],
  ['MSTR', 'MicroStrategy', 'مايكرو ستراتيجي', 'technology', 40],
];

export const US_UNIVERSE: Instrument[] = raw.map(([symbol, nameEn, nameAr, sector, cap]) => ({
  id: `us:${symbol}`,
  market: 'us' as const,
  symbol,
  nameEn,
  nameAr,
  sector,
  currency: 'USD' as const,
  marketCap: cap * 1e9,
}));

export const US_SECTORS = [
  'technology',
  'financials',
  'energy',
  'healthcare',
  'consumer',
  'industrial',
  'realestate',
  'utilities',
] as const;
